version: '3.8'

# Erweiterte docker-compose.yml mit Monitoring
services:
  borganizer:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: borganizer-app
    ports:
      - "5000:5000"
    volumes:
      - borganizer_data:/app/backend/relationship_organizer.db
      - borganizer_uploads:/app/backend/uploads
      - borganizer_logs:/app/backend/logs
    environment:
      - NODE_ENV=production
      - PORT=5000
      - LOG_LEVEL=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - borganizer-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    container_name: borganizer-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - borganizer_certs:/etc/nginx/certs:ro
      - borganizer_logs:/var/log/nginx
    depends_on:
      borganizer:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - borganizer-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Watchtower für automatische Updates (optional)
  watchtower:
    image: containrrr/watchtower
    container_name: borganizer-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400  # 24 Stunden
      - WATCHTOWER_INCLUDE_STOPPED=true
    restart: unless-stopped
    profiles:
      - monitoring

  # Portainer für Container Management (optional)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: borganizer-portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    profiles:
      - monitoring

volumes:
  borganizer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/db
  borganizer_uploads:
    driver: local  
    driver_opts:
      type: none
      o: bind
      device: ./data/uploads
  borganizer_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/logs
  borganizer_certs:
    driver: local
  portainer_data:
    driver: local

networks:
  borganizer-network:
    driver: bridge